# INPUT AND SECONDARY 
units   : input.tsv
species : alpaca
ref     : vicpac32
bucket  : wags
alias   : s3
profile : slurm

# SINGULARITY IMAGE
sif : /path/to/wags.sif

# SORTSAM TEMP DIR
tmp_dir :
  sort_tmp  : /path/to/proc/dir
  fastq_tmp : /path/to/proc/dir

# LEFT ALIGN BAM
left_align : false

# INTERVAL SIZE SCATTER
nrun_length  : 50
scatter_size : 50

# REFERENCE FILES
ref_dict  : VicPac.v3.2.dict
ref_fasta : /home/alpaca/refgen/alpaca/vicpac32/VicPac.v3.2.fa

# RESOURCE FILES FOR BQSR (OPTIONAL)

# SV CONDA ENVS
conda_envs :
  delly  : delly
  gridss : gridss
  smoove : smoove
  manta  : manta
