#!/bin/bash -l
#PBS -l walltime=6:00:00,nodes=1:ppn=2,mem=62gb
#PBS -m abe
#PBS -M cull0084@umn.edu
#PBS -o $PBS_JOBID.BREED.joint_genotype.out
#PBS -e $PBS_JOBID.BREED.joint_genotype.err
#PBS -N BREED.joint_genotype.pbs
#PBS -q mesabi

set -e

cd $PBS_O_WORKDIR
conda activate vep98

java -Dconfig.file=./cromwell.conf \
 -jar /home/fried255/cull0084/projects/gatk4_pipeline/cromwell-40.jar \
 run ./joint-discovery-gatk4-local.wdl \
 -i ./joint-discovery-gatk4-local.ALL.json
