joint_cohort : gvcfs.tsv
species      : chicken
ref          : GRCg7b
date         : ''
bucket       : ''
alias        : s3
profile      : ''

# SINGULARITY IMAGE
sif : /path/to/wags.sif

# CONDA ENV
conda_envs :
  qc : bcftools

# INTERVAL ANCHOR METHOD
anchor_type : nruns
# INTERVAL SIZES
nrun_length     : 50
interval_length : 10000000

# DB IMPORT
batch_size : 50

# REFERENCE FILES
ref_fasta : /home/refgen/chicken/GRCg7b/GCF_016699485.2_GRCg7b_genomic_nice.fa
ref_dict  : /home/refgen/chicken/GRCg7b/GCF_016699485.2_GRCg7b_genomic_nice.dict
ref_gtf   : /home/refgen/chicken/GRCg7b/MISSING.gtf
map_gaps : /path/to/map_gas.csv
var_deserts : /path/to/var_deserts.csv

# TMP DIRS
tmp_dir :
  sites_only_gather_vcf : /path/to/.sites_gather
  unfilt_gather_vcf     : /path/to/.unfilt_gather

# RECAL
snp_recalibration_tranche_values    : [
  "100.0", "99.95", "99.9", "99.5", "99.0", "98.0", 
  "97.0", "96.0", "95.0", "94.0", "93.0", "92.0", "91.0", "90.0"]
snp_recalibration_annotation_values : ["QD", "MQRankSum", "ReadPosRankSum", "FS", "MQ", "SOR", "DP"]
snp_filter_level   : 99.0

indel_recalibration_tranche_values    : [
  "100.0", "99.95", "99.9", "99.5", "99.0", "98.0", 
  "97.0", "96.0", "95.0", "94.0", "93.0", "92.0", "91.0", "90.0"]
indel_recalibration_annotation_values : ["FS", "ReadPosRankSum", "MQRankSum", "QD", "SOR", "DP"]
indel_filter_level : 99.0

# RESOURCE FILES (FROM CONTAINER)
coverage_sites : ''

# OUTPUT OPTIONS
# PHASING
phasing  : false
link_map : ''

