# INPUT AND SECONDARY 
units   : input.tsv
species : cat
ref     : Fca126_nice
bucket  : wags
alias   : s3
profile : slurm

# SINGULARITY IMAGE
sif : /path/to/wags.sif

# SORTSAM TEMP DIR
tmp_dir :
  sort_tmp  : /path/to/proc/dir
  fastq_tmp : /path/to/proc/dir

# LEFT ALIGN BAM
left_align : false

# INTERVAL SIZE SCATTER
nrun_length  : 50
scatter_size : 50

# REFERENCE FILES
ref_dict  : Fca126_mat1.0.nice.dict
ref_fasta : /home/refgen/cat/Fca126/Fca126_mat1.0.nice.fna

# RESOURCE FILES FOR BQSR (OPTIONAL)

# SV CONDA ENVS
conda_envs :
  delly  : delly
  gridss : gridss
  smoove : smoove
  manta  : manta
