joint_cohort : gvcfs.list
species      : dog
ref          : canfam4
date         : ''
bucket       : ''
alias        : s3
profile      : slurm

# SINGULARITY IMAGE
sif : /home/fried255/cull0084/.sif/wags.sif

# OUTPUT OPTIONS
var_table : true
phasing   : false

# CONDA ENV
conda_envs :
    qc : bcftools

# INTERVAL ANCHOR METHOD
anchor_type : nruns
# INTERVAL SIZES
nrun_length     : 50
interval_length : 10000000

# DB IMPORT
batch_size : 50

# REFERENCE FILES
ref_fasta : /home/refgen/dog/canfam4/canFam4.fa
ref_dict  : /home/refgen/dog/canfam4/canFam4.dict
ref_gtf   : /home/refgen/dog/canfam4/UU_Cfam_GSD_1.0_ROSY.refSeq.ensformat.gtf.gz
map_gaps : /path/to/map_gas.csv
var_deserts : /path/to/var_deserts.csv

# TMP DIRS
tmp_dir :
  sites_only_gather_vcf : /path/to/.sites_gather
  unfilt_gather_vcf     : /path/to/.unfilt_gather

# RECAL
indel_recalibration_tranche_values    : ["100.0", "99.95", "99.9", "99.5", "99.0", "97.0", "96.0", "95.0", "94.0", "93.5", "93.0", "92.0", "91.0", "90.0"]
indel_recalibration_annotation_values : ["FS", "ReadPosRankSum", "MQRankSum", "QD", "SOR", "DP"]
snp_recalibration_tranche_values      : ["100.0", "99.95", "99.9", "99.8", "99.6", "99.5", "99.4", "99.3", "99.0", "98.0", "97.0", "90.0" ]
snp_recalibration_annotation_values   : ["QD", "MQRankSum", "ReadPosRankSum", "FS", "MQ", "SOR", "DP"]

indel_filter_level : 99.7
snp_filter_level   : 99.7

# RESOURCE FILES (FROM CONTAINER)
dbsnp_indels_vcf : /home/refgen/dog/canfam4/resources/canFam4.recoded.dbsnp.151.indels.sorted.fixed.header.chr.vcf
dbsnp_snp_vcf    : /home/refgen/dog/canfam4/resources/canFam4.recoded.dbsnp.151.snps.sorted.fixed.header.chr.vcf
broad_snp_vcf    : /home/refgen/dog/canfam4/resources/canFam4.final.broad.snps.sorted.fixed.header.chr.vcf
axelsson_snp_vcf : /home/refgen/dog/canfam4/resources/canFam4.final.axelsson.snps.sorted.fixed.header.chr.vcf
illumina_snp_vcf : /home/refgen/dog/canfam4/resources/canFam4.illumina.snps.sorted.fixed.header.chr.vcf

# same coverage as UU_Cfam_GSD_1.0_ROSY (canfam4+ROSY)
coverage_sites : /home/refgen/dog/UU_Cfam_GSD_1.0_ROSY/resources/SRZ189891_722g.simp.header.CanineHD.names.GSD_1.0.filter.vcf.gz

# AF FREQ
var_to_table_dir : /panfs/roc/groups/0/fried255/fried255/working/all_dogs

# OUTPUT OPTIONS
# PHASING
phasing  : false
link_map : /home/refgen/dog/canfam4/canFam4.linkage.map
